version: '3.9'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo-6.0.4
    volumes:
      - mongo-data:/data
    ports:
      - ":27017"

  app:
    build: .
    restart: unless-stopped
    container_name: nuxt-2.15.8
    ports:
      - "80:80"
    links:
      - mongo

volumes:
  mongo-data:
